#!/usr/bin/env bash

set -Eeuo pipefail

log() {
  printf '[backup] %s\n' "$*"
}

require_env() {
  local key="$1"

  if [[ -z "${!key:-}" ]]; then
    log "Missing required environment variable: ${key}"
    exit 1
  fi
}

send_failure_email() {
  local exit_code="$1"
  local failed_command="$2"
  local line_number="$3"

  local enabled="${BACKUP_ALERT_EMAIL_ENABLED:-true}"
  if [[ "$enabled" != "true" ]]; then
    return
  fi

  local recipient="${BACKUP_ALERT_EMAIL_TO:-${ADMIN_EMAIL:-}}"
  if [[ -z "${RESEND_API_KEY:-}" || -z "${EMAIL_FROM:-}" || -z "$recipient" ]]; then
    log "Failure alert skipped because Resend variables are incomplete."
    return
  fi

  local subject="Falha no backup do SavePoint"
  local payload
  payload="$(jq -nc \
    --arg from "$EMAIL_FROM" \
    --arg to "$recipient" \
    --arg subject "$subject" \
    --arg reply_to "${EMAIL_REPLY_TO:-}" \
    --arg text "O backup automatico do SavePoint falhou.\n\nMomento: ${TIMESTAMP:-$(date --iso-8601=seconds)}\nApp: ${NEXT_PUBLIC_APP_URL:-desconhecido}\nEtapa: ${CURRENT_STAGE:-desconhecida}\nComando: ${failed_command}\nLinha: ${line_number}\nCodigo de saida: ${exit_code}\n" \
    '
      {
        from: $from,
        to: [$to],
        subject: $subject,
        text: $text
      }
      + (if ($reply_to | length) > 0 then {reply_to: $reply_to} else {} end)
    ')"

  log "Sending failure alert e-mail via Resend"
  curl --silent --show-error --fail \
    -X POST \
    -H "Authorization: Bearer ${RESEND_API_KEY}" \
    -H "Content-Type: application/json" \
    https://api.resend.com/emails \
    -d "$payload" >/dev/null || log "Failed to send Resend alert e-mail."
}

handle_error() {
  local exit_code="$1"
  local line_number="$2"
  local failed_command="$3"

  log "Backup failed at stage '${CURRENT_STAGE:-unknown}' with exit code ${exit_code}"
  printf 'stage=%s\ncommand=%s\nline=%s\nexit_code=%s\ntime=%s\n' \
    "${CURRENT_STAGE:-unknown}" \
    "$failed_command" \
    "$line_number" \
    "$exit_code" \
    "${TIMESTAMP:-$(date --iso-8601=seconds)}" >/backups/last-failure.txt 2>/dev/null || true

  send_failure_email "$exit_code" "$failed_command" "$line_number"
  exit "$exit_code"
}

github_api() {
  local method="$1"
  local url="$2"
  local data="${3:-}"

  if [[ -n "$data" ]]; then
    curl --silent --show-error --fail \
      -X "$method" \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer ${BACKUP_GITHUB_TOKEN}" \
      -H "Content-Type: application/json" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      "$url" \
      -d "$data"
    return
  fi

  curl --silent --show-error --fail \
    -X "$method" \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer ${BACKUP_GITHUB_TOKEN}" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "$url"
}

upload_to_github_release() {
  [[ "${BACKUP_GITHUB_ENABLED:-false}" == "true" ]] || return 0

  require_env BACKUP_GITHUB_TOKEN
  require_env BACKUP_GITHUB_REPOSITORY

  local repo="$BACKUP_GITHUB_REPOSITORY"
  local tag="${BACKUP_GITHUB_RELEASE_TAG:-savepoint-backups}"
  local release_url="https://api.github.com/repos/${repo}/releases/tags/${tag}"
  local release_json

  if ! release_json="$(github_api GET "$release_url" 2>/dev/null)"; then
    log "GitHub release '${tag}' not found. Creating it."
    release_json="$(github_api POST "https://api.github.com/repos/${repo}/releases" "$(jq -nc \
      --arg tag "$tag" \
      --arg name "SavePoint Backups" \
      --arg body "Encrypted automated backups generated by SavePoint." \
      '{tag_name: $tag, name: $name, body: $body, draft: false, prerelease: false}')")"
  fi

  local release_id
  release_id="$(printf '%s' "$release_json" | jq -r '.id')"
  local upload_url
  upload_url="$(printf '%s' "$release_json" | jq -r '.upload_url' | sed 's/{?name,label}//')"

  local asset_name existing_id
  for asset_path in "$ENCRYPTED_ARCHIVE" "$CHECKSUM_FILE"; do
    asset_name="$(basename "$asset_path")"
    existing_id="$(printf '%s' "$release_json" | jq -r --arg name "$asset_name" '.assets[]? | select(.name == $name) | .id' | head -n 1)"

    if [[ -n "$existing_id" ]]; then
      log "Replacing existing GitHub asset ${asset_name}"
      github_api DELETE "https://api.github.com/repos/${repo}/releases/assets/${existing_id}" >/dev/null
    fi

    log "Uploading ${asset_name} to GitHub Releases"
    curl --silent --show-error --fail \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer ${BACKUP_GITHUB_TOKEN}" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      -H "Content-Type: application/octet-stream" \
      --data-binary "@${asset_path}" \
      "${upload_url}?name=${asset_name}" >/dev/null
  done

  local keep_count="${BACKUP_GITHUB_RETENTION_COUNT:-30}"
  if [[ "$keep_count" =~ ^[0-9]+$ ]] && (( keep_count >= 0 )); then
    local release_with_assets backup_bases total_count prune_count
    release_with_assets="$(github_api GET "https://api.github.com/repos/${repo}/releases/${release_id}")"
    backup_bases="$(printf '%s' "$release_with_assets" | jq -r '
      [.assets[]
      | select(.name | endswith(".enc"))
      | { base: (.name | sub("\\.tar\\.gz\\.enc$"; "")), created_at }]
      | sort_by(.created_at)
      | .[].base
    ')"

    total_count="$(printf '%s\n' "$backup_bases" | awk 'NF' | wc -l | tr -d ' ')"
    prune_count=$(( total_count - keep_count ))

    if (( prune_count > 0 )); then
      printf '%s\n' "$backup_bases" | awk 'NF' | head -n "$prune_count" | while IFS= read -r old_base; do
        [[ -n "$old_base" ]] || continue
        log "Pruning old GitHub backup set ${old_base}"
        printf '%s' "$release_with_assets" | jq -r --arg base "$old_base" '
          .assets[]
          | select(.name | startswith($base))
          | .id
        ' | while IFS= read -r asset_id; do
          github_api DELETE "https://api.github.com/repos/${repo}/releases/assets/${asset_id}" >/dev/null
        done
      done
    fi
  fi
}

upload_to_object_storage() {
  [[ "${BACKUP_OBJECT_STORAGE_ENABLED:-false}" == "true" ]] || return 0

  require_env BACKUP_OBJECT_STORAGE_ENDPOINT
  require_env BACKUP_OBJECT_STORAGE_BUCKET
  require_env BACKUP_OBJECT_STORAGE_ACCESS_KEY
  require_env BACKUP_OBJECT_STORAGE_SECRET_KEY

  local region="${BACKUP_OBJECT_STORAGE_REGION:-sa-saopaulo-1}"
  local prefix="${BACKUP_OBJECT_STORAGE_PREFIX:-savepoint}"

  export AWS_ACCESS_KEY_ID="$BACKUP_OBJECT_STORAGE_ACCESS_KEY"
  export AWS_SECRET_ACCESS_KEY="$BACKUP_OBJECT_STORAGE_SECRET_KEY"
  export AWS_DEFAULT_REGION="$region"

  local destination_base="s3://${BACKUP_OBJECT_STORAGE_BUCKET}/${prefix}/${ARCHIVE_DATE_PATH}"

  log "Uploading encrypted archive to Object Storage"
  aws s3 cp "$ENCRYPTED_ARCHIVE" "${destination_base}/$(basename "$ENCRYPTED_ARCHIVE")" \
    --endpoint-url "$BACKUP_OBJECT_STORAGE_ENDPOINT" \
    --only-show-errors

  aws s3 cp "$CHECKSUM_FILE" "${destination_base}/$(basename "$CHECKSUM_FILE")" \
    --endpoint-url "$BACKUP_OBJECT_STORAGE_ENDPOINT" \
    --only-show-errors
}

prune_local_archives() {
  local retention_days="${BACKUP_LOCAL_RETENTION_DAYS:-14}"

  if [[ ! "$retention_days" =~ ^[0-9]+$ ]]; then
    log "Invalid BACKUP_LOCAL_RETENTION_DAYS='${retention_days}', skipping local pruning."
    return
  fi

  find /backups/archives -type f -mtime +"$retention_days" -delete 2>/dev/null || true
  find /backups/archives -type d -empty -delete 2>/dev/null || true
}

export TZ="${TZ:-America/Sao_Paulo}"
CURRENT_STAGE="initializing"

DB_HOST="${BACKUP_DB_HOST:-postgres}"
DB_PORT="${BACKUP_DB_PORT:-5432}"
DB_NAME="${POSTGRES_DB:-savepoint}"
DB_USER="${POSTGRES_USER:-savepoint}"
DB_PASSWORD="${POSTGRES_PASSWORD:-}"
WORKSPACE_ROOT="${BACKUP_WORKSPACE_ROOT:-/workspace}"
CRITICAL_PATHS="${BACKUP_CRITICAL_PATHS:-.env,docker-compose.yml,DEPLOY_AND_BOOTSTRAP.md}"

require_env POSTGRES_PASSWORD
require_env BACKUP_ENCRYPTION_PASSPHRASE

export PGPASSWORD="$DB_PASSWORD"

TIMESTAMP="$(date '+%Y-%m-%dT%H-%M-%S%z')"
ARCHIVE_DATE_PATH="$(date '+%Y/%m/%d')"
ARCHIVE_BASENAME="savepoint-backup-${TIMESTAMP}"
RUN_ROOT="/tmp/${ARCHIVE_BASENAME}"
PAYLOAD_DIR="${RUN_ROOT}/payload"
ARCHIVE_DIR="/backups/archives/${ARCHIVE_DATE_PATH}"
BUNDLE_ARCHIVE="${RUN_ROOT}/${ARCHIVE_BASENAME}.tar.gz"
ENCRYPTED_ARCHIVE="${ARCHIVE_DIR}/${ARCHIVE_BASENAME}.tar.gz.enc"
CHECKSUM_FILE="${ARCHIVE_DIR}/${ARCHIVE_BASENAME}.sha256"

trap 'rm -rf "$RUN_ROOT"' EXIT
trap 'handle_error $? $LINENO "$BASH_COMMAND"' ERR

mkdir -p "$PAYLOAD_DIR" "$ARCHIVE_DIR"

CURRENT_STAGE="database-connectivity"
log "Checking database connectivity"
pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" >/dev/null

CURRENT_STAGE="database-dump"
log "Creating database dump"
pg_dump \
  --host "$DB_HOST" \
  --port "$DB_PORT" \
  --username "$DB_USER" \
  --dbname "$DB_NAME" \
  --format=custom \
  --compress=9 \
  --no-owner \
  --no-privileges \
  --file "${PAYLOAD_DIR}/database.dump"

CURRENT_STAGE="globals-dump"
log "Creating globals dump"
pg_dumpall \
  --host "$DB_HOST" \
  --port "$DB_PORT" \
  --username "$DB_USER" \
  --globals-only | gzip -9 >"${PAYLOAD_DIR}/globals.sql.gz"

CURRENT_STAGE="critical-files"
log "Packing critical files"
critical_found=false
critical_args=()
while IFS= read -r candidate; do
  [[ -n "$candidate" ]] || continue
  if [[ -e "${WORKSPACE_ROOT}/${candidate}" ]]; then
    critical_args+=("$candidate")
    critical_found=true
  else
    log "Critical path not found, skipping: ${candidate}"
  fi
done < <(printf '%s' "$CRITICAL_PATHS" | tr ',' '\n')

if [[ "$critical_found" == "true" ]]; then
  tar -czf "${PAYLOAD_DIR}/critical-files.tar.gz" -C "$WORKSPACE_ROOT" "${critical_args[@]}"
else
  log "No critical files found for backup payload."
fi

cat <<EOF >"${PAYLOAD_DIR}/metadata.txt"
timestamp=${TIMESTAMP}
app_url=${NEXT_PUBLIC_APP_URL:-unknown}
database=${DB_NAME}
database_host=${DB_HOST}
timezone=${TZ}
critical_paths=${CRITICAL_PATHS}
EOF

CURRENT_STAGE="manifest"
(cd "$PAYLOAD_DIR" && sha256sum * > manifest.sha256)

CURRENT_STAGE="archive-encryption"
log "Creating encrypted archive"
tar -czf "$BUNDLE_ARCHIVE" -C "$PAYLOAD_DIR" .
openssl enc -aes-256-cbc -salt -pbkdf2 -iter 200000 \
  -in "$BUNDLE_ARCHIVE" \
  -out "$ENCRYPTED_ARCHIVE" \
  -pass env:BACKUP_ENCRYPTION_PASSPHRASE

sha256sum "$ENCRYPTED_ARCHIVE" | awk '{print $1}' >"$CHECKSUM_FILE"

CURRENT_STAGE="github-upload"
upload_to_github_release
CURRENT_STAGE="object-storage-upload"
upload_to_object_storage
CURRENT_STAGE="local-prune"
prune_local_archives

CURRENT_STAGE="finalizing"
date --iso-8601=seconds >/backups/last-success.txt
log "Backup finished successfully: ${ENCRYPTED_ARCHIVE}"
